# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='session',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
